### PR TITLE
allways update packages indexes

### PR DESCRIPTION
**Pull request by vamgnu**
I propose these changes to resolve [these](https://github.com/UdelaRInterior/ansible-AlternC/pull/8#discussion_r643520888) conversation. To ensure there will be no 404 errors and install the latest version of the packages.

### CODE REVIEW

**Comment by ulvida** [comment]
Sorry, I disagree, as [explain here](https://github.com/UdelaRInterior/ansible-AlternC/pull/8#discussion_r643049015). Let's eventually open the discussion with other reviewers.

**Comment by ulvida** [comment]
> Sorry, I disagree, as [explained here](https://github.com/UdelaRInterior/ansible-AlternC/pull/8#discussion_r643049015). Let's eventually open the discussion with other reviewers.

**Comment by ulvida** [comment]
Alternative solution proposed here:  f617850  , that ensures one and only one `apt update` in the our previous to the installation of the package.

**Comment by vamgnu** [comment]
it was solved by [PR13](https://github.com/UdelaRInterior/ansible-AlternC/pull/13).

**Pull request closed without merging**
